/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */
#include "AndroidApplicationModel.h"
#include "JniUTFString.h"
#include "ApplicationModel.h"
#include "AndroidAudioDeviceProvider.h"

using namespace CppUtils;

/*
 * Class:     com.neborosoft.vx.logic.AndroidApplicationModel
 * Method:    private final void initNative(android.content.Context context, java.lang.String sfzPath, java.lang.String metronomeDataPath)
 * Signature: (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)V
 */
void AndroidApplicationModel::initNative(JNIEnv* env,
                                         jobject thiz,
                                         jobject context,
                                         jstring sfzPath,
                                         jstring metronomeDataPath) {
    JniUTFString sfz(sfzPath, env);
    ApplicationModel::init(JniUTFString(sfzPath, env).getData(),
                           JniUTFString(metronomeDataPath, env).getData());
    AndroidAudioDeviceProvider::init(env, context);
}