/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

/* C++ header file for class com/neborosoft/vx/logic/AndroidApplicationModel */
#pragma once

#include <jni.h>


namespace AndroidApplicationModel {

// DO NOT modify
    static constexpr auto FULL_CLASS_NAME = u8"com/neborosoft/vx/logic/AndroidApplicationModel";


/*
 * Class:     com.neborosoft.vx.logic.AndroidApplicationModel
 * Method:    private final void initNative(android.content.Context context, java.lang.String sfzPath, java.lang.String metronomeDataPath)
 * Signature: (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)V
 */
    void JNICALL initNative(JNIEnv* env, jobject thiz, jobject context, jstring sfzPath, jstring metronomeDataPath);

/**
* register Native functions
* @returns success or not
*/
    inline bool registerNativeFunctions(JNIEnv* env) {
// 1. C++20 has u8"" string as char8_t type, we should cast them.
// 2. jni.h has JNINativeMethod::name as char* type not const char*. (while Android does)
#define jenny_u8cast(u8) const_cast<char *>(reinterpret_cast<const char *>(u8))
        const JNINativeMethod gsNativeMethods[] = {
                {
                        /* method name      */ jenny_u8cast(u8"initNative"),
                        /* method signature */ jenny_u8cast(u8"(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)V"),
                        /* function pointer */ reinterpret_cast<void *>(initNative)
                }
        };

        const int gsMethodCount = sizeof(gsNativeMethods) / sizeof(JNINativeMethod);

        bool success = false;
        jclass clazz = env->FindClass(jenny_u8cast(FULL_CLASS_NAME));
        if (clazz != nullptr) {
            success = !env->RegisterNatives(clazz, gsNativeMethods, gsMethodCount);
            env->DeleteLocalRef(clazz);
        }
        return success;
#undef jenny_u8cast
    }

} // endof namespace AndroidApplicationModel


